In [88]:
import numpy as np
import pandas as pd

In [111]:
df=pd.read_csv('housePrice.csv', na_values=' ')

In [112]:
# drop samples with unknown addresses
df.dropna(axis=0, how='any', inplace=True)

In [91]:
for item in df['Area']:
    if ',' in item:
        df['Area'].replace({item:item.replace(',','').replace(' ','')}, inplace=True)
df['Area']=pd.to_numeric(df['Area'])

In [92]:
# drop outliers
df=df[df['Area']<=2000]

In [93]:
x=df[['Area', 'Room', 'Parking', 'Warehouse', 'Elevator', 'Address']]
y=df['Price(USD)']

In [94]:
x=pd.get_dummies(data=x, columns=['Parking', 'Warehouse', 'Elevator', 'Address'])
x

,Area,Room,Parking_False,Parking_True,Warehouse_False,Warehouse_True,Elevator_False,Elevator_True,Address_Abazar,Address_Abbasabad,...,Address_Waterfall,Address_West Ferdows Boulevard,Address_West Pars,Address_Yaftabad,Address_Yakhchiabad,Address_Yousef Abad,Address_Zafar,Address_Zaferanieh,Address_Zargandeh,Address_Zibadasht
0,63,1,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,60,1,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,79,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,95,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,123,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3474,86,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3475,83,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3476,75,2,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3477,105,2,0,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3478,82,2,1,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
msk=np.random.rand(len(df))<0.8
train_x=x[msk]
train_y=y[msk]
test_x=x[~msk]
test_y=y[~msk]

In [96]:
from sklearn import linear_model

In [97]:
regr=linear_model.LinearRegression()
regr.fit(train_x, train_y)
print('Coefficients: ', regr.coef_)
print("Intercept: ", regr.intercept_)

Coefficients:  [ 2.04645489e+03  2.49601667e+04  1.06925297e+04 -1.06925297e+04
 -6.82061766e+01  6.82061766e+01  5.46340851e+03 -5.46340851e+03
  3.64556065e+04  4.17169446e+04 -7.93728639e+05 -2.36204256e+03
 -3.35433521e+04  6.37171305e+03 -2.54454930e+04  2.36095829e+05
 -2.03854502e+04 -5.69303809e+04  5.37082472e+04 -1.99571781e+04
 -2.57563313e+04 -8.97898031e+04  3.12298869e+05  8.79391244e+04
  2.36034348e+05 -9.04932027e+04 -4.83425279e+04 -9.53342828e+03
 -1.55773141e+04 -1.28395772e+05 -4.95825887e+04  3.49245965e-10
 -2.77930410e+04 -3.94216579e+04  2.22594201e+04  1.74622983e-10
 -2.13298980e+05  9.80464210e+03  1.06571794e+05 -4.30687172e+05
  7.95791586e+04  2.43762310e+04  6.02833212e+04 -5.29478425e+04
 -3.93573368e+04  1.61491028e+05  1.60709529e+04  1.80240049e+05
  1.91317562e+04  5.52901903e+02  5.93371548e+04  1.14060014e+05
  4.94372149e+05 -1.54188159e+04 -2.83084956e+03 -8.08033440e+04
  1.54229183e+04 -8.68186408e+03  3.73823995e+05 -4.08857168e+04
  8.78104286e+03 -7.77828605e+04 -8.68676245e+04 -4.36557457e-11
  2.69471583e+04  1.22989904e+05 -6.32358384e+04  1.11378671e+05
  9.31632436e+04  3.23319422e+04 -8.05472538e+04 -8.99751428e+04
 -1.27031577e+04 -2.65905963e+03 -1.60050881e+04  1.23009885e+05
  4.77996141e+04 -8.03380892e+04 -3.33060226e+04 -7.64024515e+04
 -1.22419218e+05 -6.28110582e+04 -1.67263170e+04  4.32511407e+04
 -9.72920340e+04  3.38382844e+05 -2.97778869e+03 -9.90844007e+03
  5.82076609e-11 -3.66833787e+04  1.09139364e-10 -1.32729236e+03
 -5.04645246e+03 -3.09455990e+04 -5.28392609e+03  7.47136135e+05
  7.17600324e+03  1.78741135e+04  1.29301844e+05 -1.16520274e+05
 -6.42793745e+04  6.44218246e+04 -6.64139502e+04 -5.09317033e-11
  3.39358092e+04  1.63023380e+05  7.07549402e+03 -4.52457816e+04
  1.20428656e+04 -8.35496173e+04 -3.24361290e+04  3.22124030e+03
  3.11062997e+04  3.06003946e+05  6.43293768e+04 -6.33420984e+04
  2.71702826e+03  4.04701065e+04 -7.49324841e+02 -9.76835944e+03
  6.61343724e+04 -1.43880836e+05 -8.81450068e+04 -8.93666032e+04
  3.43997646e+03 -1.00416298e+05  8.32950110e+04 -7.17201689e+04
 -1.13680844e+04 -8.88383044e+04  2.76001754e+04  9.22307292e+03
 -9.78541985e+04 -1.48768854e+04 -4.30732700e+04 -1.53825135e+04
 -4.31603913e+04  3.74483627e+04  4.10604221e+04 -5.45329326e+04
 -2.60682768e+04 -1.62963247e+04 -1.00391156e+05  1.10932358e+05
 -1.38810584e+05 -3.64007056e+03 -4.83679217e+04  1.38243195e-10
 -1.46440784e+05 -1.39465748e+04  1.21911213e+04 -1.84837179e+04
 -1.15242376e+04 -2.81302755e+05 -4.73161669e+03 -1.91528166e+04
 -2.18520796e+04 -8.67201141e+04  1.84970674e+05 -1.17249690e+05
 -8.72874439e+04 -8.21662389e+04 -2.04872624e+04  4.42469940e+04
  8.91134413e+03 -9.30771624e+04  1.65813917e+04 -1.86705804e+04
 -2.38500649e+04  2.61823159e+04 -1.29077756e+05  1.76935440e+04
  2.20405800e+04  2.95087969e+04  3.25467971e+05 -1.35461501e+04
 -2.21182606e+04 -4.34166293e+04 -3.80763600e+04 -7.17684083e+04
 -4.63872853e+03 -2.10909595e+03  1.01242085e+04 -1.07276156e+05
 -3.21518239e+04  6.67636315e+05 -1.42892750e+06  3.24472198e+05
 -3.55248631e-08 -5.99994744e+03 -3.64159708e+04  2.41301827e+04
 -7.65953781e+03 -5.72276826e+04 -5.89902562e+04  5.17312083e+04
  1.71823809e+05  4.74357556e+05  5.62473176e+04 -1.52879993e+04]
Intercept:  -108886.91448448875

In [98]:
from sklearn.metrics import r2_score

In [99]:
test_y=np.asanyarray(test_y)
test_y_=regr.predict(test_x)
print("Mean absolute error: %.2f"%np.mean(np.absolute(test_y_-test_y)))
print('Residual sum of squares (MSE): %.2f'%np.mean((test_y_-test_y)**2))
print("R2_score: %.2f"%r2_score(test_y, test_y_))

Mean absolute error: 70811.10
Residual sum of squares (MSE): 27067206283.17
R2_score: 0.70